# Start from the python image
FROM python:3.8

# Define working directory inside container
WORKDIR /home/python/app

# Copy source
COPY . .

# start the python interpreter
ENTRYPOINT ["python3", "markov.py"]

# run the python script markov.py
# CMD ["5", "5"]


