services:
  frontend:
    image: example-frontend
    ports:
      - "5000:5000"
    build: 
      context: front

  backend:
    image: example-backend
    ports:
      - "8000:8000" 
    build:
      context: back
    restart: unless-stopped


